2024-07-05 20:36:42,160 - my_logger - ERROR - Exception occurred
Traceback (most recent call last):
  File "C:\Users\localadmin\AppData\Local\Temp\ipykernel_11656\3757565777.py", line 19, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
2024-07-05 20:36:42,160 - my_logger - DEBUG - This is a debug message
2024-07-05 20:36:42,160 - my_logger - INFO - This is an info message
2024-07-05 20:36:42,160 - my_logger - WARNING - This is a warning message
2024-07-05 20:36:42,161 - my_logger - ERROR - This is an error message
2024-07-05 20:36:42,161 - my_logger - CRITICAL - This is a critical message
2024-07-05 20:37:42,330 - my_logger - ERROR - Exception occurred
Traceback (most recent call last):
  File "C:\Users\localadmin\AppData\Local\Temp\ipykernel_11656\2488903820.py", line 19, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
2024-07-05 20:37:42,330 - my_logger - ERROR - Exception occurred
Traceback (most recent call last):
  File "C:\Users\localadmin\AppData\Local\Temp\ipykernel_11656\2488903820.py", line 19, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
2024-07-05 20:37:48,707 - my_logger - ERROR - Exception occurred
Traceback (most recent call last):
  File "C:\Users\localadmin\AppData\Local\Temp\ipykernel_11656\2488903820.py", line 19, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
2024-07-05 20:37:48,707 - my_logger - ERROR - Exception occurred
Traceback (most recent call last):
  File "C:\Users\localadmin\AppData\Local\Temp\ipykernel_11656\2488903820.py", line 19, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
2024-07-05 20:37:48,707 - my_logger - ERROR - Exception occurred
Traceback (most recent call last):
  File "C:\Users\localadmin\AppData\Local\Temp\ipykernel_11656\2488903820.py", line 19, in <module>
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
